import{a as f,i as s}from"./assets/vendor-DfBcrOrC.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function n(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(e){if(e.ep)return;e.ep=!0;const i=n(e);fetch(e.href,i)}})();async function g({name:t,email:o,phone:n,form:r}){try{const e=await f.get("https://jsonplaceholder.typicode.com/posts",{params:{name:t,email:o,phone:n}});s.success({title:"Запит успішно відправлено",position:"topCenter"}),r.reset()}catch(e){console.error(e)}}const u=document.getElementById("ticketForm"),y=document.querySelectorAll(".concerts-button"),c=document.querySelector(".modal"),L=document.querySelector(".modal-close");y.forEach(t=>{t.addEventListener("click",()=>{c.classList.add("active"),document.body.classList.add("modal-open")})});function m(){c.classList.remove("active"),document.body.classList.remove("modal-open")}L.addEventListener("click",()=>{m()});c.addEventListener("click",t=>{t.target===c&&m()});document.addEventListener("keydown",t=>{t.key==="Escape"&&(c!=null&&c.classList.contains("active"))&&(console.log(t.key),m())});u.addEventListener("submit",function(t){t.preventDefault();const o=new FormData(u),n=(o.get("user-name")||"").trim(),r=(o.get("user-email")||"").trim(),e=(o.get("user-phone")||"").trim();if(n){if(n.length<2){s.error({title:"Помилка валідації",message:"Введіть коректне ім'я",position:"topCenter"});return}}else{s.error({title:"Помилка валідації",message:"Введіть своє ім'я",position:"topCenter"});return}if(!r.includes("@")||!r.includes(".")){s.error({title:"Помилка валідації",message:"Введіть свою коректну електронну адресу",position:"topCenter"});return}if(e){if(e.length<10){s.error({title:"Помилка валідації",message:"Введіть коректний номер телефону",position:"topCenter"});return}}else{s.error({title:"Помилка валідації",message:"Введіть номер телефону",position:"topCenter"});return}s.success({title:"Вітаємо!",message:"Ваш білет заброньовано",position:"topCenter"}),g({name:n,email:r,phone:e,form:u})});const v={BASE_URL:"/Serhii-Lishchynskyi-Trainee-Front-end-Developer/",DEV:!1,MODE:"production",PROD:!0,SSR:!1},E="8799335287:AAGsViaK01PtOKkqAAmm7w_alGFrKwJMQLU",h="7382601286";async function C(t){const o=`
Привіт, ${t}!

Ми — гурт G&G 🎸
Ми отримали ваше повідомлення.

Дякуємо за відгук 💛
Ми стаємо кращими завдяки вам!
`,n=`https://api.telegram.org/bot${E}/sendMessage`;try{await f.post(n,{chat_id:h,text:o})}catch(r){console.error(r)}}console.log("TOKEN:",void 0);console.log("CHAT_ID:",void 0);console.log("ENV TEST:",v);console.log("TOKEN LENGTH:",void 0);const l=document.getElementById("contactsForm");l&&l.addEventListener("submit",t=>{t.preventDefault();const o=new FormData(l),n=(o.get("user-name")||"").trim(),r=(o.get("user-email")||"").trim(),e=(o.get("user-notice")||"").trim();if(n){if(n.length<2){s.error({title:"Помилка валідації",message:"Введіть коректне ім'я",position:"topCenter"});return}}else{s.error({title:"Помилка валідації",message:"Введіть своє ім'я",position:"topCenter"});return}if(!r.includes("@")||!r.includes(".")){s.error({title:"Помилка валідації",message:"Введіть свою коректну електронну адресу",position:"topCenter"});return}if(!e){s.error({title:"Помилка валідації",message:"Введіть своє повідомлення",position:"topCenter"});return}C(n),s.success({title:"Ваше повідомлення отримано",position:"topCenter"}),l.reset()});const S=document.querySelector("[data-menu-open]"),b=document.querySelector("[data-menu-close]"),a=document.querySelector("[data-menu]"),D=document.querySelectorAll(".mobile-menu-link");S.addEventListener("click",()=>{a.classList.add("active"),document.body.classList.add("modal-open")});function p(){a.classList.remove("active"),document.body.classList.remove("modal-open")}b.addEventListener("click",()=>{p()});document.addEventListener("keydown",t=>{t.key==="Escape"&&(a!=null&&a.classList.contains("active"))&&p()});D.forEach(t=>{t.addEventListener("click",()=>{p()})});
//# sourceMappingURL=index.js.map
